{% set version = "1.7-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pbapply
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pbapply_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pbapply/pbapply_{{ version }}.tar.gz
  sha256: 64b8e931e0a09031c20b66173ce80a646043b8f135d329bc86226a11c6b706c0

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('pbapply')"           # [not win]
    - "\"%R%\" -e \"library('pbapply')\""  # [win]

about:
  home: https://github.com/psolymos/pbapply
  license: GPL-2.0-only
  summary: A lightweight package that adds progress bar to vectorized R functions ('*apply'). The implementation can easily be added to functions where showing the progress is useful (e.g. bootstrap). The type and style of the progress bar (with percentages or remaining time) can be set through options. Supports several
    parallel processing backends.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: pbapply
# Type: Package
# Title: Adding Progress Bar to '*apply' Functions
# Version: 1.4-2
# Date: 2019-08-30
# Author: Peter Solymos [aut, cre], Zygmunt Zawadzki [aut]
# Maintainer: Peter Solymos <solymos@ualberta.ca>
# Description: A lightweight package that adds progress bar to vectorized R functions ('*apply'). The implementation can easily be added to functions where showing the progress is useful (e.g. bootstrap). The type and style of the progress bar (with percentages or remaining time) can be set through options. Supports several parallel processing backends.
# Depends: R (>= 3.2.0)
# Imports: parallel
# License: GPL-2
# URL: https://github.com/psolymos/pbapply
# BugReports: https://github.com/psolymos/pbapply/issues
# NeedsCompilation: no
# Packaged: 2019-08-31 02:39:23 UTC; Peter
# Repository: CRAN
# Date/Publication: 2019-08-31 05:10:02 UTC
