travis:
  secure:
    BINSTAR_TOKEN: h9v+BvpUrd2Y/c8hPmeVxQxqnXIdOGNe78rqDaBoomQw3UqqqSW4XFtYJFX0PpnX1eC5gdrLpUlmzWk6X7lc6OiThGcF45d4EltlAmKSe/WKxyZLfjuoqFlO+qBetlx1diYxhwN0l8WSwh+rHH0uzRc/kqIbGdHCDNHT0vfVUKutxuLTgrAx2Ld27yS0cUN4shGebDLhRUCmErpedPgQ53XV39sqAyMczDXtivKqKfAIgIvz6D01VXVI3M9JBBHmQF4GGtKmB8qgJiygaG3YB1c7B05elV4TsMHM1hBB9c6aFlH8U52RZgm5DJH6hwJfNwNUOs0vMf54MseUaPw2+E32u5N+T7OXqKIjiKaAL8Y40mRhi4zcMno63PEEIT579yVFov3jv/7MFwYvxaqjXL0spMQDUzfZZOl/QeFcHVZd0ktKEt8SJ8oKJ9Ze0q47w2Vt3WChSfsuOmRLcRRYvFrO8J1QnMfLfBl92EhWToCeAw4OfMDfScfoPBrHeZBoiQalSRR9MYjVaXsEjGfLRE3tYBoqk695yoePLSPrm87yu4j78cHakzhWWjxVqUhz0W048XpMQu5qkGInMZsSoIbtV9oqUzaTEsKtdC4pnqwFdaW2zt/rzlkyfwHuWitZcmLLs0rtTa7LBiVysNlWSVO8HABGiRe1dHtRo6ptmjE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
