appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: XRitVTZXtaOyYRceJFNWyEmNynHFV0To3MdxCxbPeYkVtUPm+Rk3IrFrcFxDOofiljovhJppW/lYeD5D8UXOLPR7o4i3djVLre/l9VLfm18svEhxM9lkW8xPNVoG881pt1SEWDeQvu+LKigdAnk4SVNcThN0HhTyJ73ARoaG2VGsHsXaziVe7OL1uHkcArA63N3yP2P6X0kmkDomfLiAaRFTPGvDFC7vtuTNdpSgN/N4qMgh+DNc1H0cisNST5uzywS4ZMJXZa1TC04gfuO/Tdx94J5+Aec7drCoBGBN/TOZ7NwRkPgmtdgJgto6+Fv9t2rDCe2RNRNeU6IgLUQILed8DPKvy8znjTMXDz8ePlqytANE504U3p1k8pEiMRx3HniV66Z1OIgE8ZSGYqjEUNK0LOXAs1vDix8DsIyLtFKjyJYaXyGUJCxIKPraxDXEQz+/6WpWwifEFuCLQYoLadT9E6gPhvz82Ok9B6AKUc2M10jCsjVwGcE9p/e9fuEOzZJRpIUu3l5nUluSEfupifk9FWPa9fmk1qnWhjDID0b5skBt7rqLXweJyl++8fsXdqvCSNvkpecFl3tpT2THL9HOAR3CeHCkj+NXhX52jbyT6vLJtt/kCW0NVcGvEclk67/t9ZeH/samFZxJHyr6mbrzYEfqntAeQGKLcTCx8eA=
conda_forge_output_validation: true
